### ISSUE TITLE
Tooltips on Label fields

### ISSUE THREAD

**Issue by lhayhurst** [furiouscollective/gridforms#64]
Hi, love your library, use it to great effect to create sexy forms. Thank you!

Do you have any pro tips on adding help text info tooltips to your labels? Hover over label is ok but doesn't really give the user visual feedback that info is avail, and <i> icons usually mess up the clean look and field of the label data-field.

Cheers

**Comment by kumailht** [comment]
Thank you Lyle. What do you think about showing a tooltip that only appears on focus?
